blank_issues_enabled: true
contact_links:
  - name: 文档
    url: https://as.js.cool
    about: 仔细阅读文档
  - name: 说点什么
    url: https://github.com/asunajs/asuna/discussions
    about: 如果您不是反馈问题，只是单纯聊聊，请使用 discussions 频道
