name: Changesets
on:
  push:
    branches:
      - release
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "git-checks=false" >> .npmrc

      - name: install dependencies
        run: pnpm install

      - name: create and publish versions
        uses: changesets/action@v1.4.6
        with:
          publish: pnpm ci:publish
          version: pnpm ci:version
          commit: "ci: changesets versions"
          title: "ci: changesets versions"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
